/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annexurei;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import patient.NewPatient;

import AUDIT.*;
import BloodTest.*;
import Controlpanel.ControlPanel;
import MMQa.*;
import MMQb.*;
import Q_LES_QSF.*;
import TLFB.*;
import java.awt.Toolkit;


/**
 *
 * @author Udayanga
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Connection conn;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public Main() {
        initComponents();
        setDisable();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BTN_EXIST = new javax.swing.JButton();
        BTN_EXIST1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXT_NAME = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        T6_1 = new javax.swing.JButton();
        T6_2 = new javax.swing.JButton();
        T6_3 = new javax.swing.JButton();
        T6_4 = new javax.swing.JButton();
        T6_5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        T12_1 = new javax.swing.JButton();
        T12_2 = new javax.swing.JButton();
        T12_3 = new javax.swing.JButton();
        T12_4 = new javax.swing.JButton();
        T12_5 = new javax.swing.JButton();
        T12_6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        T0_1 = new javax.swing.JButton();
        T0_2 = new javax.swing.JButton();
        T0_3 = new javax.swing.JButton();
        T0_4 = new javax.swing.JButton();
        T0_5 = new javax.swing.JButton();
        T0_6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_PATIENT = new javax.swing.JTable();
        TXT_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));

        jButton1.setText("New Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTN_EXIST.setText("Exist Patient");
        BTN_EXIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EXISTActionPerformed(evt);
            }
        });

        BTN_EXIST1.setText("Control Panel");
        BTN_EXIST1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EXIST1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_EXIST, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_EXIST1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTN_EXIST, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(BTN_EXIST1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));

        jLabel1.setText("Select Patient");

        jLabel2.setText("Name");

        TXT_NAME.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)), "T-6"));

        T6_1.setText("Enter");
        T6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6_1ActionPerformed(evt);
            }
        });

        T6_2.setText("Enter");
        T6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6_2ActionPerformed(evt);
            }
        });

        T6_3.setText("Enter");
        T6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6_3ActionPerformed(evt);
            }
        });

        T6_4.setText("Enter");
        T6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6_4ActionPerformed(evt);
            }
        });

        T6_5.setText("Enter");
        T6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6_5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Blood test");

        jLabel8.setText("Q LES Q SF");

        jLabel7.setText("MMQb");

        jLabel6.setText("MMQa");

        jLabel5.setText("TLFB");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T6_4)
                    .addComponent(T6_5)
                    .addComponent(T6_1)
                    .addComponent(T6_2)
                    .addComponent(T6_3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(T6_1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T6_2))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T6_3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T6_4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T6_5)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)), "T-12"));

        jLabel10.setText("AUDIT");

        T12_1.setText("Enter");
        T12_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T12_1ActionPerformed(evt);
            }
        });

        T12_2.setText("Enter");
        T12_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T12_2ActionPerformed(evt);
            }
        });

        T12_3.setText("Enter");
        T12_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T12_3ActionPerformed(evt);
            }
        });

        T12_4.setText("Enter");
        T12_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T12_4ActionPerformed(evt);
            }
        });

        T12_5.setText("Enter");
        T12_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T12_5ActionPerformed(evt);
            }
        });

        T12_6.setText("Enter");
        T12_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T12_6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Blood test");

        jLabel12.setText("Q LES Q SF");

        jLabel13.setText("MMQb");

        jLabel14.setText("MMQa");

        jLabel15.setText("TLFB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T12_5)
                    .addComponent(T12_6)
                    .addComponent(T12_1)
                    .addComponent(T12_2)
                    .addComponent(T12_3)
                    .addComponent(T12_4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(T12_1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(T12_2))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T12_3))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T12_4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T12_5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T12_6)
                    .addComponent(jLabel11))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)), "T-0"));

        jLabel16.setText("AUDIT");

        T0_1.setText("Enter");
        T0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T0_1ActionPerformed(evt);
            }
        });

        T0_2.setText("Enter");
        T0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T0_2ActionPerformed(evt);
            }
        });

        T0_3.setText("Enter");
        T0_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T0_3ActionPerformed(evt);
            }
        });

        T0_4.setText("Enter");
        T0_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T0_4ActionPerformed(evt);
            }
        });

        T0_5.setText("Enter");
        T0_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T0_5ActionPerformed(evt);
            }
        });

        T0_6.setText("Enter");
        T0_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T0_6ActionPerformed(evt);
            }
        });

        jLabel17.setText("Blood test");

        jLabel18.setText("Q LES Q SF");

        jLabel19.setText("MMQb");

        jLabel20.setText("MMQa");

        jLabel21.setText("TLFB");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T0_5)
                    .addComponent(T0_6)
                    .addComponent(T0_1)
                    .addComponent(T0_2)
                    .addComponent(T0_3)
                    .addComponent(T0_4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(T0_1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(T0_2))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T0_3))
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T0_4)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T0_5)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T0_6)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TBL_PATIENT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBL_PATIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_PATIENTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TBL_PATIENTMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_PATIENT);

        TXT_ID.setEditable(false);
        TXT_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_IDActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_IDActionPerformed

    private void TBL_PATIENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_PATIENTMouseClicked
        try{
            String T0_audit="",T0_tlfb="",T0_mmqa="",T0_mmqb="",T0_qles_qsf="",T0_blood="",
                    T6_tlfb="",T6_mmqa="",T6_mmqb="",T6_qles_qsf="",T6_blood="",
                    T12_audit="",T12_tlfb="",T12_mmqa="",T12_mmqb="",T12_qles_qsf="",T12_blood="";
            DBHelpPatientTable db= new DBHelpPatientTable();
            int row=TBL_PATIENT.getSelectedRow();
            String table_click_id=(TBL_PATIENT.getModel().getValueAt(row, 0).toString());
            TXT_ID.setText(TBL_PATIENT.getModel().getValueAt(row, 0).toString());
            TXT_NAME.setText(TBL_PATIENT.getModel().getValueAt(row, 1).toString());
            
            rs=db.getState(new Patient(table_click_id));
            if(rs.next()){
                T0_audit=rs.getString("T0_audit");
                if("n".equals(T0_audit))T0_1.setEnabled(true);
                if("y".equals(T0_audit))T0_1.setEnabled(false);
                T0_tlfb=rs.getString("T0_tlfb");
                if("n".equals(T0_tlfb))T0_2.setEnabled(true);
                if("y".equals(T0_tlfb))T0_2.setEnabled(false);
                T0_mmqa=rs.getString("T0_mmqa");
                if("n".equals(T0_mmqa))T0_3.setEnabled(true);
                if("y".equals(T0_mmqa))T0_3.setEnabled(false);
                T0_mmqb=rs.getString("T0_mmqb");
                if("n".equals(T0_mmqb))T0_4.setEnabled(true);
                if("y".equals(T0_mmqb))T0_4.setEnabled(false);
                T0_qles_qsf=rs.getString("T0_qles_qsf");
                if("n".equals(T0_qles_qsf))T0_5.setEnabled(true);
                if("y".equals(T0_qles_qsf))T0_5.setEnabled(false);
                T0_blood=rs.getString("T0_blood");
                if("n".equals(T0_blood))T0_6.setEnabled(true);
                if("y".equals(T0_blood))T0_6.setEnabled(false);
                
                T6_tlfb=rs.getString("T6_tlfb");
                if("n".equals(T6_tlfb))T6_1.setEnabled(true);
                if("y".equals(T6_tlfb))T6_1.setEnabled(false);
                T6_mmqa=rs.getString("T6_mmqa");
                if("n".equals(T6_mmqa))T6_2.setEnabled(true);
                if("y".equals(T6_mmqa))T6_2.setEnabled(false);
                T6_mmqb=rs.getString("T6_mmqb");
                if("n".equals(T6_mmqb))T6_3.setEnabled(true);
                if("y".equals(T6_mmqb))T6_3.setEnabled(false);
                T6_qles_qsf=rs.getString("T6_qles_qsf");
                if("n".equals(T6_qles_qsf))T6_4.setEnabled(true);
                if("y".equals(T6_qles_qsf))T6_4.setEnabled(false);
                T6_blood=rs.getString("T6_blood");
                if("n".equals(T6_blood))T6_5.setEnabled(true);
                if("y".equals(T6_blood))T6_5.setEnabled(false);
                
                T12_audit=rs.getString("T12_audit");
                if("n".equals(T12_audit))T12_1.setEnabled(true);
                if("y".equals(T12_audit))T12_1.setEnabled(false);
                T12_tlfb=rs.getString("T12_tlfb");
                if("n".equals(T12_tlfb))T12_2.setEnabled(true);
                if("y".equals(T12_tlfb))T12_2.setEnabled(false);
                T12_mmqa=rs.getString("T12_mmqa");
                if("n".equals(T12_mmqa))T12_3.setEnabled(true);
                if("y".equals(T12_mmqa))T12_3.setEnabled(false);
                T12_mmqb=rs.getString("T12_mmqb");
                if("n".equals(T12_mmqb))T12_4.setEnabled(true);
                if("y".equals(T12_mmqb))T12_4.setEnabled(false);
                T12_qles_qsf=rs.getString("T12_qles_qsf");
                if("n".equals(T12_qles_qsf))T12_5.setEnabled(true);
                if("y".equals(T12_qles_qsf))T12_5.setEnabled(false);
                T12_blood=rs.getString("T12_blood");
                if("n".equals(T12_blood))T12_6.setEnabled(true);
                 if("y".equals(T12_blood))T12_6.setEnabled(false);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_TBL_PATIENTMouseClicked

    private void BTN_EXISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXISTActionPerformed
        DBHelpPatientTable db= new DBHelpPatientTable();
        TBL_PATIENT.setModel(DbUtils.resultSetToTableModel(db.getNameID()));
        
    }//GEN-LAST:event_BTN_EXISTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        patient.NewPatient np= new NewPatient();
        np.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void T0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T0_1ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        AUDIT ad= new AUDIT();
        ad.setidName(new CallAudit(id, name,"t0"));
        ad.setVisible(true);
        
    }//GEN-LAST:event_T0_1ActionPerformed

    private void T0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T0_2ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        TLFB bt= new TLFB();
        bt.setidName(new CallTlfb(id, name,"t0"));
        bt.setVisible(true);
    }//GEN-LAST:event_T0_2ActionPerformed

    private void T0_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T0_3ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        MMQa bt= new MMQa();
        bt.setidName(new CallMmqa(id, name,"t0"));
        bt.setVisible(true);
    }//GEN-LAST:event_T0_3ActionPerformed

    private void T0_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T0_4ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        MMQb bt= new MMQb();
        bt.setidName(new CallMmqb(id, name,"t0"));
        bt.setVisible(true);
    }//GEN-LAST:event_T0_4ActionPerformed

    private void T0_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T0_5ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        Q_LES_Q_SF bt= new Q_LES_Q_SF();
        bt.setidName(new CallQLesQSf(id, name,"t0"));
        bt.setVisible(true);
    }//GEN-LAST:event_T0_5ActionPerformed

    private void T0_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T0_6ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        Bloodtest bt= new Bloodtest();
        bt.setidName(new CallBloodtest(id, name,"t0"));
        bt.setVisible(true);
    }//GEN-LAST:event_T0_6ActionPerformed

    private void T6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6_1ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        TLFB bt= new TLFB();
        bt.setidName(new CallTlfb(id, name,"t6"));
        bt.setVisible(true);
    }//GEN-LAST:event_T6_1ActionPerformed

    private void T12_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T12_2ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        TLFB bt= new TLFB();
        bt.setidName(new CallTlfb(id, name,"t12"));
        bt.setVisible(true);
    }//GEN-LAST:event_T12_2ActionPerformed

    private void T12_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T12_1ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        AUDIT ad= new AUDIT();
        ad.setidName(new CallAudit(id, name,"t12"));
        ad.setVisible(true);
    }//GEN-LAST:event_T12_1ActionPerformed

    private void T6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6_2ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        MMQa bt= new MMQa();
        bt.setidName(new CallMmqa(id, name,"t6"));
        bt.setVisible(true);
    }//GEN-LAST:event_T6_2ActionPerformed

    private void T12_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T12_3ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        MMQa bt= new MMQa();
        bt.setidName(new CallMmqa(id, name,"t12"));
        bt.setVisible(true);
    }//GEN-LAST:event_T12_3ActionPerformed

    private void T6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6_3ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        MMQb bt= new MMQb();
        bt.setidName(new CallMmqb(id, name,"t6"));
        bt.setVisible(true);
    }//GEN-LAST:event_T6_3ActionPerformed

    private void T12_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T12_4ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        MMQb bt= new MMQb();
        bt.setidName(new CallMmqb(id, name,"t12"));
        bt.setVisible(true);
    }//GEN-LAST:event_T12_4ActionPerformed

    private void T6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6_4ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        Q_LES_Q_SF bt= new Q_LES_Q_SF();
        bt.setidName(new CallQLesQSf(id, name,"t6"));
        bt.setVisible(true);
    }//GEN-LAST:event_T6_4ActionPerformed

    private void T12_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T12_5ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        Q_LES_Q_SF bt= new Q_LES_Q_SF();
        bt.setidName(new CallQLesQSf(id, name,"t12"));
        bt.setVisible(true);
    }//GEN-LAST:event_T12_5ActionPerformed

    private void T6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6_5ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        Bloodtest bt= new Bloodtest();
        bt.setidName(new CallBloodtest(id, name,"t6"));
        bt.setVisible(true);
    }//GEN-LAST:event_T6_5ActionPerformed

    private void T12_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T12_6ActionPerformed
        String id=TXT_ID.getText();
        String name=TXT_NAME.getText();
        
        Bloodtest bt= new Bloodtest();
        bt.setidName(new CallBloodtest(id, name,"t12"));
        bt.setVisible(true);
    }//GEN-LAST:event_T12_6ActionPerformed

    private void TBL_PATIENTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_PATIENTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TBL_PATIENTMouseEntered

    private void BTN_EXIST1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXIST1ActionPerformed
        Controlpanel.ControlPanel cp= new ControlPanel();
        cp.setVisible(true);
        
    }//GEN-LAST:event_BTN_EXIST1ActionPerformed

    private void setDisable(){
        T0_1.setEnabled(false);T0_2.setEnabled(false);T0_3.setEnabled(false);T0_4.setEnabled(false);T0_5.setEnabled(false);T0_6.setEnabled(false);
        T6_1.setEnabled(false);T6_2.setEnabled(false);T6_3.setEnabled(false);T6_4.setEnabled(false);T6_5.setEnabled(false);
        T12_1.setEnabled(false);T12_2.setEnabled(false);T12_3.setEnabled(false);T12_4.setEnabled(false);T12_5.setEnabled(false);T12_6.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_EXIST;
    private javax.swing.JButton BTN_EXIST1;
    private javax.swing.JButton T0_1;
    private javax.swing.JButton T0_2;
    private javax.swing.JButton T0_3;
    private javax.swing.JButton T0_4;
    private javax.swing.JButton T0_5;
    private javax.swing.JButton T0_6;
    private javax.swing.JButton T12_1;
    private javax.swing.JButton T12_2;
    private javax.swing.JButton T12_3;
    private javax.swing.JButton T12_4;
    private javax.swing.JButton T12_5;
    private javax.swing.JButton T12_6;
    private javax.swing.JButton T6_1;
    private javax.swing.JButton T6_2;
    private javax.swing.JButton T6_3;
    private javax.swing.JButton T6_4;
    private javax.swing.JButton T6_5;
    private javax.swing.JTable TBL_PATIENT;
    private javax.swing.JTextField TXT_ID;
    private javax.swing.JTextField TXT_NAME;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
