/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient;


/**
 *
 * @author Udayanga
 */
import state.state;
import state.DBHelpState;
import annexurei.DBHelpPatientTable;
import javax.swing.JOptionPane;

import annexurei.*;
import MINI.*;
public class NewPatient extends javax.swing.JFrame {

    /**
     * Creates new form NewPatient
     */
    String gender;
    String religion;
    String race;
    String alcohol_dependence_current,alcohol_abuse_current,psychotic_disoeder_current,psychotic_disoeder_lifetime;
    public NewPatient() {
        initComponents();
        GP_GENDER.add(G_MALE);GP_GENDER.add(G_FEMALE);GP_GENDER.add(G_OTHER);
        GP_RELIGION.add(R_BUDD);GP_RELIGION.add(R_CHI);GP_RELIGION.add(R_HIN);GP_RELIGION.add(R_ISLM);GP_RELIGION.add(R_NO);GP_RELIGION.add(R_OTHER);
        GP__RACE.add(RA_SIN);GP__RACE.add(RA_TAML);GP__RACE.add(RA_OTHER);GP__RACE.add(RA_MUSLM);
        MINI_1.add(M_1_N);MINI_1.add(M_1_y);
        MINI_2.add(M_2_N);MINI_2.add(M_2_NA);MINI_2.add(M_2_Y);
        MINI_3.add(M_3_N);MINI_3.add(M_3_Y);
        MINI_4.add(M_4_N);MINI_4.add(M_4_Y);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GP_GENDER = new javax.swing.ButtonGroup();
        GP_RELIGION = new javax.swing.ButtonGroup();
        GP__RACE = new javax.swing.ButtonGroup();
        MINI_1 = new javax.swing.ButtonGroup();
        MINI_2 = new javax.swing.ButtonGroup();
        MINI_3 = new javax.swing.ButtonGroup();
        MINI_4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BD_YEAY = new javax.swing.JTextField();
        BD_MONTH = new javax.swing.JTextField();
        BD_DATE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        R_YEAR = new javax.swing.JTextField();
        R_MONTH = new javax.swing.JTextField();
        R_DATE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        G_MALE = new javax.swing.JRadioButton();
        G_FEMALE = new javax.swing.JRadioButton();
        G_OTHER = new javax.swing.JRadioButton();
        R_BUDD = new javax.swing.JRadioButton();
        R_HIN = new javax.swing.JRadioButton();
        R_CHI = new javax.swing.JRadioButton();
        R_ISLM = new javax.swing.JRadioButton();
        R_NO = new javax.swing.JRadioButton();
        R_OTHER = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        RA_SIN = new javax.swing.JRadioButton();
        RA_TAML = new javax.swing.JRadioButton();
        RA_MUSLM = new javax.swing.JRadioButton();
        RA_OTHER = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        TOWN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EMP = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CONTACT_PERSN = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        ADRESS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DIOGNOSIS = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        MOTIVATION = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        AGE = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        REFERED = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        M_1_y = new javax.swing.JRadioButton();
        M_1_N = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        M_2_Y = new javax.swing.JRadioButton();
        M_2_N = new javax.swing.JRadioButton();
        M_2_NA = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        M_3_Y = new javax.swing.JRadioButton();
        M_3_N = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        M_4_Y = new javax.swing.JRadioButton();
        M_4_N = new javax.swing.JRadioButton();
        BTN_ADD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add New Patient");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Patient's Details"));

        jLabel2.setText("Name");

        NAME.setToolTipText("At least 2 names,or 1name with more than 1 initial");

        jLabel3.setText("ID Number");

        BD_YEAY.setToolTipText("Year");

        BD_MONTH.setToolTipText("Month");

        BD_DATE.setToolTipText("Date");

        jLabel4.setText("Date of Birth");

        jLabel5.setText("Register Date");

        R_YEAR.setToolTipText("Year");

        R_MONTH.setToolTipText("Month");

        R_DATE.setToolTipText("Date");

        jLabel6.setText("Gender");

        G_MALE.setText("Male");
        G_MALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_MALEActionPerformed(evt);
            }
        });

        G_FEMALE.setText("Female");
        G_FEMALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_FEMALEActionPerformed(evt);
            }
        });

        G_OTHER.setText("Other");
        G_OTHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_OTHERActionPerformed(evt);
            }
        });

        R_BUDD.setText("Buddhism");
        R_BUDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_BUDDActionPerformed(evt);
            }
        });

        R_HIN.setText("Hinduism");
        R_HIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_HINActionPerformed(evt);
            }
        });

        R_CHI.setText("Christianity/Catholicisim");
        R_CHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_CHIActionPerformed(evt);
            }
        });

        R_ISLM.setText("Islam");
        R_ISLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_ISLMActionPerformed(evt);
            }
        });

        R_NO.setText("No Religion");
        R_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_NOActionPerformed(evt);
            }
        });

        R_OTHER.setText("Other");
        R_OTHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_OTHERActionPerformed(evt);
            }
        });

        jLabel7.setText("Religion");

        RA_SIN.setText("Sinhala");
        RA_SIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RA_SINActionPerformed(evt);
            }
        });

        RA_TAML.setText("Tamil");
        RA_TAML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RA_TAMLActionPerformed(evt);
            }
        });

        RA_MUSLM.setText("Muslim");
        RA_MUSLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RA_MUSLMActionPerformed(evt);
            }
        });

        RA_OTHER.setText("Other");
        RA_OTHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RA_OTHERActionPerformed(evt);
            }
        });

        jLabel8.setText("Race");

        jLabel9.setText("Town/Village");

        EMP.setColumns(20);
        EMP.setRows(5);
        EMP.setToolTipText("Please discribe as much as possible; e.g. Unskilled manual worker at a local factory wich produce gas cookers, No regular job-odd unskilled manualy jobs if he finds any.  ");
        jScrollPane1.setViewportView(EMP);

        jLabel10.setText("Employement");

        jLabel11.setText("Email");

        jLabel12.setText("Telephone");

        CONTACT_PERSN.setColumns(20);
        CONTACT_PERSN.setRows(5);
        CONTACT_PERSN.setToolTipText("If participant cannot be contacted with their details.");
        jScrollPane2.setViewportView(CONTACT_PERSN);

        jLabel13.setText("Contact Person");

        ADRESS.setToolTipText("Postal adress of usual residence");

        jLabel14.setText("Adress");

        jLabel15.setText("Refered by");

        DIOGNOSIS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harmfull use of alcohol", "Alcohol dependence syndrome", "Psychotic" }));

        jLabel16.setText("Diognosis");

        MOTIVATION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Low" }));

        jLabel17.setText("Level of Motivation ");

        AGE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "35 or below", "Above 35" }));

        jLabel18.setText("Age");

        REFERED.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPD-NHSL", "Ward-NHSL", "Private Doctor", "Other" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(NAME)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11))
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R_BUDD)
                                    .addComponent(G_MALE)
                                    .addComponent(RA_SIN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RA_TAML)
                                    .addComponent(G_FEMALE)
                                    .addComponent(R_HIN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(G_OTHER)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(R_CHI)
                                            .addComponent(RA_MUSLM))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RA_OTHER)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(R_ISLM)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(R_NO)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(R_OTHER))))))
                            .addComponent(AGE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MOTIVATION, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DIOGNOSIS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(R_YEAR)
                                    .addComponent(BD_YEAY, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(R_MONTH, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(BD_MONTH))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BD_DATE, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(R_DATE)))
                            .addComponent(jScrollPane2)
                            .addComponent(ADRESS)
                            .addComponent(EMAIL)
                            .addComponent(jScrollPane1)
                            .addComponent(TP)
                            .addComponent(TOWN)
                            .addComponent(REFERED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BD_YEAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BD_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BD_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G_MALE)
                    .addComponent(G_FEMALE)
                    .addComponent(G_OTHER)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_BUDD)
                    .addComponent(R_HIN)
                    .addComponent(R_CHI)
                    .addComponent(R_ISLM)
                    .addComponent(R_NO)
                    .addComponent(R_OTHER)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RA_SIN)
                    .addComponent(RA_TAML)
                    .addComponent(RA_MUSLM)
                    .addComponent(RA_OTHER)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOWN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(REFERED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DIOGNOSIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOTIVATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "MINI"));

        jLabel19.setText("Alcohol dependence (Current)");

        M_1_y.setText("Yes");
        M_1_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_1_yActionPerformed(evt);
            }
        });

        M_1_N.setText("No");
        M_1_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_1_NActionPerformed(evt);
            }
        });

        jLabel20.setText("Alcohol Abuse (Current)");

        M_2_Y.setText("Yes");
        M_2_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_2_YActionPerformed(evt);
            }
        });

        M_2_N.setText("No");
        M_2_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_2_NActionPerformed(evt);
            }
        });

        M_2_NA.setText("N/A");
        M_2_NA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_2_NAActionPerformed(evt);
            }
        });

        jLabel21.setText("Psychotic disorder (Current)");

        M_3_Y.setText("Yes");
        M_3_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_3_YActionPerformed(evt);
            }
        });

        M_3_N.setText("No");
        M_3_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_3_NActionPerformed(evt);
            }
        });

        jLabel22.setText("Psychotic disorder (Lifetime)");

        M_4_Y.setText("Yes");
        M_4_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_4_YActionPerformed(evt);
            }
        });

        M_4_N.setText("No");
        M_4_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_4_NActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(M_1_y)
                        .addGap(18, 18, 18)
                        .addComponent(M_1_N))
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(M_2_Y)
                        .addGap(18, 18, 18)
                        .addComponent(M_2_N)
                        .addGap(18, 18, 18)
                        .addComponent(M_2_NA))
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(M_3_Y)
                        .addGap(18, 18, 18)
                        .addComponent(M_3_N))
                    .addComponent(jLabel22)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(M_4_Y)
                        .addGap(18, 18, 18)
                        .addComponent(M_4_N)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_1_y)
                    .addComponent(M_1_N))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_2_Y)
                    .addComponent(M_2_N)
                    .addComponent(M_2_NA))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_3_Y)
                    .addComponent(M_3_N))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_4_Y)
                    .addComponent(M_4_N))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTN_ADD.setText("Add");
        BTN_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ADDActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_ADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ADDActionPerformed
//        if(NAME.getText()!="" && ID.getText()!=""&& ADRESS.getText()!=""&& BD_DATE.getText()!=""
//                && BD_MONTH.getText()!=""&& BD_YEAY.getText()!=""&&
//                CONTACT_PERSN.getText()!=""&& EMAIL.getText()!=""&& EMP.getText()!=""&& ID.getText()!=""
//                && NAME.getText()!=""&& R_DATE.getText()!=""&& R_MONTH.getText()!=""&& R_YEAR.getText()!=""
//                && TOWN.getText()!=""&& TP.getText()!=""){
//            JOptionPane.showMessageDialog(null, "Please Enter all fields");
//        }
//        else{
            try{
            String id=ID.getText(),name=NAME.getText(),town=TOWN.getText(),employeement=EMP.getText()
                ,date_birth=BD_YEAY.getText()+"-"+BD_MONTH.getText()+"-"+BD_DATE.getText(),
                register_date=R_YEAR.getText()+"-"+R_MONTH.getText()+"-"+R_DATE.getText(),
                date_t6="",date_t12="",email=EMAIL.getText(),telephone=TP.getText(),contact_person=CONTACT_PERSN.getText(),
                adress=ADRESS.getText(),refered_by=REFERED.getSelectedItem().toString(),age=AGE.getSelectedItem().toString(),
                dignosis=DIOGNOSIS.getSelectedItem().toString(),level_motivation=MOTIVATION.getSelectedItem().toString();
            
            DBHelpPatientTable db= new DBHelpPatientTable();
            db.addPatientTable(new Patient(id, name, gender, religion, race, town, employeement, date_birth, register_date, register_date, register_date, email, telephone, contact_person, adress, refered_by, age, dignosis, level_motivation));
            DBHelpState db2= new DBHelpState();
            db2.addState(new state(id, "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n"));
            DBHelpMini db3= new DBHelpMini();
            db3.addMini(new mini(alcohol_dependence_current, alcohol_abuse_current, psychotic_disoeder_current, psychotic_disoeder_lifetime, id));
            this.setVisible(false);
            Main m= new Main();
            m.setVisible(true);
            }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage()+"Add Button");
            
//        }
        ADRESS.setText("");
        BD_DATE.setText("");
        BD_MONTH.setText("");
        BD_YEAY.setText("");
        CONTACT_PERSN.setText("");
        EMAIL.setText("");
        EMP.setText("");
        ID.setText("");
        NAME.setText("");
        R_DATE.setText("");
        R_MONTH.setText("");
        R_YEAR.setText("");
        TOWN.setText("");
        TP.setText("");
    }
        
            
        
    }//GEN-LAST:event_BTN_ADDActionPerformed

    private void G_MALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_MALEActionPerformed
        gender="Male";
        // TODO add your handling code here:
    }//GEN-LAST:event_G_MALEActionPerformed

    private void G_FEMALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_FEMALEActionPerformed
        gender="Female";        // TODO add your handling code here:
    }//GEN-LAST:event_G_FEMALEActionPerformed

    private void G_OTHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_OTHERActionPerformed
        gender="Other";    
        // TODO add your handling code here:
    }//GEN-LAST:event_G_OTHERActionPerformed

    private void R_BUDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_BUDDActionPerformed
        religion="Buddhism";
        // TODO add your handling code here:
    }//GEN-LAST:event_R_BUDDActionPerformed

    private void R_HINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_HINActionPerformed
        religion="Hinduism";        // TODO add your handling code here:
    }//GEN-LAST:event_R_HINActionPerformed

    private void R_CHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_CHIActionPerformed
        religion="Christianity/Catholicisim";
// TODO add your handling code here:
    }//GEN-LAST:event_R_CHIActionPerformed

    private void R_ISLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_ISLMActionPerformed
        religion="Islam";
        // TODO add your handling code here:
    }//GEN-LAST:event_R_ISLMActionPerformed

    private void R_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_NOActionPerformed
        religion="No Religion";
        // TODO add your handling code here:
    }//GEN-LAST:event_R_NOActionPerformed

    private void R_OTHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_OTHERActionPerformed
        religion="Other";
        // TODO add your handling code here:
    }//GEN-LAST:event_R_OTHERActionPerformed

    private void RA_SINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RA_SINActionPerformed
        race="Sinhala";
        // TODO add your handling code here:
    }//GEN-LAST:event_RA_SINActionPerformed

    private void RA_TAMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RA_TAMLActionPerformed
        race="Tamil";
        // TODO add your handling code here:
    }//GEN-LAST:event_RA_TAMLActionPerformed

    private void RA_MUSLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RA_MUSLMActionPerformed
        race="Muslim";
        // TODO add your handling code here:
    }//GEN-LAST:event_RA_MUSLMActionPerformed

    private void RA_OTHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RA_OTHERActionPerformed
        race="Other";
        // TODO add your handling code here:
    }//GEN-LAST:event_RA_OTHERActionPerformed

    private void M_1_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_1_yActionPerformed
        alcohol_dependence_current="yes";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_1_yActionPerformed

    private void M_1_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_1_NActionPerformed
        alcohol_dependence_current="no";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_1_NActionPerformed

    private void M_2_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_2_YActionPerformed
        alcohol_abuse_current="yes";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_2_YActionPerformed

    private void M_2_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_2_NActionPerformed
        alcohol_abuse_current="no";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_2_NActionPerformed

    private void M_2_NAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_2_NAActionPerformed
        alcohol_abuse_current="na";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_2_NAActionPerformed

    private void M_3_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_3_YActionPerformed
        psychotic_disoeder_current="yes";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_3_YActionPerformed

    private void M_3_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_3_NActionPerformed
        psychotic_disoeder_current="no";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_3_NActionPerformed

    private void M_4_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_4_YActionPerformed
        psychotic_disoeder_lifetime="yes";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_4_YActionPerformed

    private void M_4_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_4_NActionPerformed
        psychotic_disoeder_lifetime="no";
        // TODO add your handling code here:
    }//GEN-LAST:event_M_4_NActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ADRESS.setText("");
        BD_DATE.setText("");
        BD_MONTH.setText("");
        BD_YEAY.setText("");
        CONTACT_PERSN.setText("");
        EMAIL.setText("");
        EMP.setText("");
        ID.setText("");
        NAME.setText("");
        R_DATE.setText("");
        R_MONTH.setText("");
        R_YEAR.setText("");
        TOWN.setText("");
        TP.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();     
        Main m= new Main();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADRESS;
    private javax.swing.JComboBox<String> AGE;
    private javax.swing.JTextField BD_DATE;
    private javax.swing.JTextField BD_MONTH;
    private javax.swing.JTextField BD_YEAY;
    private javax.swing.JButton BTN_ADD;
    private javax.swing.JTextArea CONTACT_PERSN;
    private javax.swing.JComboBox<String> DIOGNOSIS;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextArea EMP;
    private javax.swing.ButtonGroup GP_GENDER;
    private javax.swing.ButtonGroup GP_RELIGION;
    private javax.swing.ButtonGroup GP__RACE;
    private javax.swing.JRadioButton G_FEMALE;
    private javax.swing.JRadioButton G_MALE;
    private javax.swing.JRadioButton G_OTHER;
    private javax.swing.JTextField ID;
    private javax.swing.ButtonGroup MINI_1;
    private javax.swing.ButtonGroup MINI_2;
    private javax.swing.ButtonGroup MINI_3;
    private javax.swing.ButtonGroup MINI_4;
    private javax.swing.JComboBox<String> MOTIVATION;
    private javax.swing.JRadioButton M_1_N;
    private javax.swing.JRadioButton M_1_y;
    private javax.swing.JRadioButton M_2_N;
    private javax.swing.JRadioButton M_2_NA;
    private javax.swing.JRadioButton M_2_Y;
    private javax.swing.JRadioButton M_3_N;
    private javax.swing.JRadioButton M_3_Y;
    private javax.swing.JRadioButton M_4_N;
    private javax.swing.JRadioButton M_4_Y;
    private javax.swing.JTextField NAME;
    private javax.swing.JRadioButton RA_MUSLM;
    private javax.swing.JRadioButton RA_OTHER;
    private javax.swing.JRadioButton RA_SIN;
    private javax.swing.JRadioButton RA_TAML;
    private javax.swing.JComboBox<String> REFERED;
    private javax.swing.JRadioButton R_BUDD;
    private javax.swing.JRadioButton R_CHI;
    private javax.swing.JTextField R_DATE;
    private javax.swing.JRadioButton R_HIN;
    private javax.swing.JRadioButton R_ISLM;
    private javax.swing.JTextField R_MONTH;
    private javax.swing.JRadioButton R_NO;
    private javax.swing.JRadioButton R_OTHER;
    private javax.swing.JTextField R_YEAR;
    private javax.swing.JTextField TOWN;
    private javax.swing.JTextField TP;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
